[compatibility]
schema = 1

[itamae]
repo = "gomeshun/itamae"
path = "itamae"
ref = "9a4fca2175e999c5dd72989d66c8ac3b6e8db978"

[sashimi-c]
repo = "gomeshun/sashimi-c"
path = "sashimi-c"
ref = "56dcf51b48ac235963817455c2d6830e7568a989"

[sashimi-si]
repo = "gomeshun/sashimi-si"
path = "sashimi-si"
ref = "673c4c32af844f2a242ae47e8906d89c202c8494"

[sashimi-w]
repo = "gomeshun/sashimi-w"
path = "sashimi-w"
ref = "88d0ec598a5d54d198cd35c49316ad658c37531e"

[sashimi-f]
repo = "gomeshun/sashimi-f"
path = "sashimi-f"
ref = "5852cf463f7a6305e29b34a52e7c8a0658d27ee5"
