[compatibility]
schema = 1

[itamae]
repo = "gomeshun/itamae"
path = "itamae"
ref = "66ee7e35d0932ff6cdc7221761e909082d9170b5"

[sashimi-c]
repo = "gomeshun/sashimi-c"
path = "sashimi-c"
ref = "3ad602d64cdb6bd68b610d20270b5fe8c4597af6"

[sashimi-si]
repo = "gomeshun/sashimi-si"
path = "sashimi-si"
ref = "fb3483bea49c8ba29e9909823b2931fa85ad6247"

[sashimi-w]
repo = "gomeshun/sashimi-w"
path = "sashimi-w"
ref = "61fcd329b5dd94ef8b0e590e89c0302de9097e6a"

[sashimi-f]
repo = "gomeshun/sashimi-f"
path = "sashimi-f"
ref = "070e3a184c7bf8c04e60863b491275136247f40c"
