[compatibility]
schema = 1

[itamae]
repo = "gomeshun/itamae"
path = "itamae"
ref = "a557a0d975b284c9fc3fe9697746e4847783653b"

[sashimi-c]
repo = "gomeshun/sashimi-c"
path = "sashimi-c"
ref = "7676dda063c068fe1301d0fe303b3fd915fa6d16"

[sashimi-si]
repo = "gomeshun/sashimi-si"
path = "sashimi-si"
ref = "c09192cde71902a976ca2a5e1d57901438264e28"

[sashimi-w]
repo = "gomeshun/sashimi-w"
path = "sashimi-w"
ref = "16ce6fb7f3507927706d7206fc06817b020b2206"

[sashimi-f]
repo = "gomeshun/sashimi-f"
path = "sashimi-f"
ref = "55227c4cbf1b4f170869b035cf9d2860e1e7d8e5"
