["compatibility"]
"schema" = 1

["itamae"]
"repo" = "gomeshun/itamae"
"path" = "itamae"
"ref" = "6d8ee62b65793df9b799977cbf1859b5233d4059"

["sashimi-c"]
"repo" = "gomeshun/sashimi-c"
"path" = "sashimi-c"
"ref" = "2caa94d990f034f17f8bdb32ca7d9c5ac0d50fd5"

["sashimi-si"]
"repo" = "gomeshun/sashimi-si"
"path" = "sashimi-si"
"ref" = "7cfbeb60fccd87150cf80a7b54c191eddf0a15a5"

["sashimi-w"]
"repo" = "gomeshun/sashimi-w"
"path" = "sashimi-w"
"ref" = "0b3146678e68ea71735173e4effb313f872fb9b9"

["sashimi-f"]
"repo" = "gomeshun/sashimi-f"
"path" = "sashimi-f"
"ref" = "3a34188347ccc6e795e6fb640f9db1870ff4383b"
